#!/usr/bin/env node

import { createHash } from 'crypto';
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'fs';
import { join } from 'path';
import { execFileSync } from 'child_process';
import subsetFont from 'subset-font';

const GENERATED_POSTS_DIR = 'posts';
const GENERATED_INDEX_FILE = 'index.html';
const GENERATED_FONT_DIR = join('fonts', 'subset');

const FONT_SOURCES = [
  { file: 'BareunBatangOTFPro-1.woff2', weight: 300 },
  { file: 'BareunBatangOTFPro-2.woff2', weight: 500 },
  { file: 'BareunBatangOTFPro-3.woff2', weight: 700 },
];

const RUNTIME_TEXT = [
  '정 진우',
  '인사',
  '생각한 것들',
  'GitHub ↗',
  'Jinwoo Jeong. All rights reserved.',
  '©',
  '↑',
  '↗',
  '“”‘’',
  '0123456789',
].join('');

function cleanGeneratedContent() {
  if (existsSync(GENERATED_POSTS_DIR)) {
    rmSync(GENERATED_POSTS_DIR, { recursive: true, force: true });
  }
  if (existsSync(GENERATED_FONT_DIR)) {
    rmSync(GENERATED_FONT_DIR, { recursive: true, force: true });
  }
  const cssDir = 'css';
  if (existsSync(cssDir)) {
    for (const entry of readdirSync(cssDir)) {
      if (/^generated-fonts(\.[0-9a-f]+)?\.css$/.test(entry)) {
        rmSync(join(cssDir, entry), { force: true });
      }
    }
  }
}

function runContentBuild() {
  execFileSync('node', ['convert.mjs', '--all'], { stdio: 'inherit' });
}

function walkHtmlFiles(dir) {
  if (!existsSync(dir)) {
    return [];
  }

  const entries = readdirSync(dir).sort();
  const files = [];

  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      files.push(...walkHtmlFiles(fullPath));
      continue;
    }
    if (fullPath.endsWith('.html')) {
      files.push(fullPath);
    }
  }

  return files;
}

function decodeHtmlEntities(text) {
  return text
    .replace(/&#x([0-9a-f]+);/gi, (_, hex) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#([0-9]+);/g, (_, dec) => String.fromCodePoint(parseInt(dec, 10)))
    .replace(/&nbsp;/g, ' ')
    .replace(/&copy;/g, '©')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&');
}

function extractRenderedText(html) {
  return decodeHtmlEntities(
    html
      .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, ' ')
      .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, ' ')
      .replace(/<!--[\s\S]*?-->/g, ' ')
      .replace(/<[^>]+>/g, ' ')
      .replace(/\s+/g, ' ')
      .trim(),
  );
}

function buildCharacterSet() {
  const htmlFiles = [GENERATED_INDEX_FILE, ...walkHtmlFiles(GENERATED_POSTS_DIR)].filter(path => existsSync(path));
  const combinedText = htmlFiles
    .map(filePath => extractRenderedText(readFileSync(filePath, 'utf8')))
    .join('\n');

  const chars = new Set();
  for (const char of `${combinedText}\n${RUNTIME_TEXT}`) {
    chars.add(char);
  }

  return [...chars].join('');
}

async function generateSubsetFonts(text) {
  mkdirSync(GENERATED_FONT_DIR, { recursive: true });

  const cssLines = [
    '/* Auto-generated by build.mjs. Do not edit manually. */',
    '',
  ];

  for (const font of FONT_SOURCES) {
    const sourcePath = join('fonts', font.file);
    const sourceBuffer = readFileSync(sourcePath);
    const subsetBuffer = await subsetFont(sourceBuffer, text, {
      targetFormat: 'woff2',
    });
    const hash = createHash('sha256').update(subsetBuffer).digest('hex').slice(0, 10);
    const fileName = `BareunBatang-${font.weight}-${hash}.woff2`;
    const outputPath = join(GENERATED_FONT_DIR, fileName);

    writeFileSync(outputPath, subsetBuffer);

    cssLines.push('@font-face {');
    cssLines.push('  font-family: "BareunBatang";');
    cssLines.push(`  src: url("/${outputPath.replaceAll('\\', '/')}") format("woff2");`);
    cssLines.push(`  font-weight: ${font.weight};`);
    cssLines.push('  font-style: normal;');
    cssLines.push('  font-display: swap;');
    cssLines.push('}');
    cssLines.push('');

    const savedBytes = sourceBuffer.length - subsetBuffer.length;
    console.log(
      `  ✓ ${fileName} (${(sourceBuffer.length / 1024).toFixed(1)}KB -> ${(subsetBuffer.length / 1024).toFixed(1)}KB, saved ${(savedBytes / 1024).toFixed(1)}KB)`,
    );
  }

  const cssContent = `${cssLines.join('\n')}\n`;
  const cssHash = createHash('sha256').update(Buffer.from(cssContent, 'utf8')).digest('hex').slice(0, 10);
  const cssFileName = `generated-fonts.${cssHash}.css`;
  const cssOutputPath = join('css', cssFileName);
  writeFileSync(cssOutputPath, cssContent);
  console.log(`  ✓ ${cssOutputPath}`);

  return cssFileName;
}

function rewriteHtmlReferences(cssFileName) {
  const hashedHref = `/css/${cssFileName}`;
  const htmlFiles = [GENERATED_INDEX_FILE, ...walkHtmlFiles(GENERATED_POSTS_DIR)].filter(p => existsSync(p));
  const pattern = /((?:href|src)\s*=\s*["'])\/css\/generated-fonts(?:\.[0-9a-f]+)?\.css(["'])/gi;
  for (const filePath of htmlFiles) {
    const original = readFileSync(filePath, 'utf8');
    const rewritten = original.replace(pattern, `$1${hashedHref}$2`);
    if (rewritten !== original) {
      writeFileSync(filePath, rewritten);
    }
  }
}

function verifyNoBareRefs() {
  const htmlFiles = [GENERATED_INDEX_FILE, ...walkHtmlFiles(GENERATED_POSTS_DIR)].filter(p => existsSync(p));
  const barePattern = /(?:^|[^A-Za-z0-9._-])\/css\/generated-fonts\.css(?:[^A-Za-z0-9._-]|$)/g;
  for (const filePath of htmlFiles) {
    const content = readFileSync(filePath, 'utf8');
    const matches = content.match(barePattern);
    if (matches && matches.length > 0) {
      throw new Error(`Bare /css/generated-fonts.css reference survived in ${filePath} (${matches.length} match(es))`);
    }
  }
}

function verifyExactlyOneHashedRef(cssFileName) {
  const htmlFiles = [GENERATED_INDEX_FILE, ...walkHtmlFiles(GENERATED_POSTS_DIR)].filter(p => existsSync(p));
  const needle = `href="/css/${cssFileName}"`;
  for (const filePath of htmlFiles) {
    const content = readFileSync(filePath, 'utf8');
    let count = 0;
    let idx = 0;
    while ((idx = content.indexOf(needle, idx)) !== -1) {
      count += 1;
      idx += needle.length;
    }
    if (count !== 1) {
      throw new Error(`Expected exactly one ${needle} in ${filePath}, found ${count}`);
    }
  }
}

async function main() {
  cleanGeneratedContent();
  runContentBuild();

  const text = buildCharacterSet();
  const glyphCount = [...text].length;

  console.log(`\nSubsetting fonts from ${glyphCount} unique characters...`);
  const cssFileName = await generateSubsetFonts(text);
  rewriteHtmlReferences(cssFileName);
  verifyNoBareRefs();
  verifyExactlyOneHashedRef(cssFileName);
}

main().catch((error) => {
  console.error('\nFont subset build failed.');
  console.error(error);
  process.exit(1);
});
